version: '3'

services:

  articles-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CONFIG_FILE: config/config.yml
    ports:
      - "4007:4007"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - my_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGODB_DATABASE: articles
    ports:
      - 27017:27017
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

